### PR TITLE
Jeff test status

### PR DESCRIPTION
**Pull request by Jeffreyricketts**
Small [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=kctraveler&utm_campaign=badge_info)

Adding a Pull Request Status Badge

### CODE REVIEW

**Comment by Jeffreyricketts** [comment]
[Pull Request](https://github.com/Jeffreyricketts/github-actions/actions/workflows/deploy.yml)
Here is the Badge added

**Comment by Jeffreyricketts** [comment]
Added clarification for Badges
image

**Comment by Jeffreyricketts** [comment]
Added info for the coverage badge:
image

**Comment by kctraveler** [comment]
@Jeffreyricketts can you remove the last part with the pull request status and that .yml from the workflow portion.

The main repo has a workflow that runs when pull request to the main branch are submitted so we can already see that it is passing. 
image

**Comment by Jeffreyricketts** [comment]
@kctraveler As in the pull request badge? Because I don't see either of them in the workflow for your main branch.

**Pull request merged**
